customer/urls.py
from django.urls import path

from .views import CustomerLoginView, ChangePasswordView, RegisterView, CustomerProfileView, \
    SendLinkResetPasswordView, Set_New_Password, EditProfileView, customer_logout, add_address, remove_address

app_name = 'customer'

urlpatterns = [
    path('login/', CustomerLoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('logout/', customer_logout, name="logout"),
    path('reset-password/', SendLinkResetPasswordView.as_view(), name="reset-password"),
    path('set-new-password/<uidb64>/<token>/', Set_New_Password, name="set-new-password"),
    path('change-password/', ChangePasswordView.as_view(), name="change_password"),
    path('profile/', CustomerProfileView.as_view(), name="profile"),
    path('edit-profile/', EditProfileView.as_view(), name="edit_profile"),
    path('add-address/', add_address, name="add_address"),
    path('remove-address/<int:address_id>', remove_address, name="remove_address"),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from online_shop import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customers/', include('customers.urls')),
    # path('products/', include('products.urls')),
    # path('orders/', include('orders.urls')),
    path('api/v1/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.cart_actions import cart_add, cart_detail, cart_remove
from orders.views import OrdersHistoryView, RecentOrdersView, order, checkout_order, payment, invoice

app_name = 'orders'

urlpatterns = [
    path('orders-history/', OrdersHistoryView.as_view(), name="orders-history"),
    path('recent-orders/', RecentOrdersView.as_view(), name="recent-orders"),
    path('add_to_cart/<int:product_id>/', cart_add, name="cart_add"),
    path('cart_detail/', cart_detail, name="cart_detail"),
    path('cart_remove/<int:product_id>/', cart_remove, name="cart_remove"),
    path('order/', order, name="order"),
    path('checkout_order/', checkout_order, name="checkout_order"),
    path('payment/<int:order_id>/', payment, name="payment"),
    path('invoice/<int:order_id>/', invoice, name="invoice"),

]

products/urls.py
from django.urls import path

from products.views import IndexView, product_by_category,ProductDetailView

app_name = 'products'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category_product/<int:pk>/', product_by_category, name='product_category'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),

]

shop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import change_lang

urlpatterns = [
    path('change_lang', change_lang, name='change_lang'),
    # path('orders/', include('orders.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('customer/', include('customer.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('core.api.urls')),

)

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')), ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load i18n %}
    {% load base_tags %}
    {% get_current_language as LANGUAGE_CODE %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}Our shop{% endblock %}</title>
    {% block style.css %}{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
          integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
            integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
            crossorigin="anonymous"></script>

    <!-- direction for persian language-->
    {% if LANGUAGE_CODE == 'fa' %}
        <link href="{% static 'base/css/rtl.css' %}" rel="stylesheet"/>
    {% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/category.css' %}">
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'base/css/base.css' %}" rel="stylesheet"/>
</head>
<body style="background-color: darkcyan; ">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-dark p-0">
    <div class="container">
        <a class="navbar-brand bi bi-house-door text-success" style="font-size: 70px" aria-current="page"
           href="{% url 'products:index' %}">{% translate "" %}</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <!--Search-->
{#                <div>#}
{#                    <div class="input-group">#}
{#                        <input type="search" class="form-control rounded" placeholder="{% translate 'Search' %}"#}
{#                               aria-label="{% translate 'Search' %}"#}
{#                               aria-describedby="search-addon"/>#}
{#                        <button type="button"#}
{#                                class="btn btn-outline-light ml-1 rounded">{% translate 'Search' %}</button>#}
{#                    </div>#}
{#                </div>#}
            </ul>

            {% if user.is_authenticated %}
                <a class="btn btn-outline-light mr-2" href="{% url 'orders:cart_detail' %}">
                    <i class="bi-cart-fill me-1"></i>
                    {% translate 'Cart' %}
                    <span class="badge bg-dark text-white ms-1 rounded-pill"></span>
                </a>
            {% else %}
                <a class="btn btn-outline-light" href="{% url 'orders:cart_detail' %}">
                    <i class="bi-cart-fill me-1"></i>
                    {% translate 'Cart' %}
                    <span class="badge bg-dark text-white ms-1 rounded-pill"></span>
                </a>
            {% endif %}
            <div class=" dropdown m-2 ">
                <button class=" dropdown-toggle  btn btn-outline-light" id="navbarDropdown" href="#"
                        role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">{% translate 'Categories' %} </button>
                {% category %}

                {#            <button type="button" class="btn btn-outline-dark m-1"> {% translate 'Categories' %}</button>#}
            </div>
            <!--person icon for watching of profile and my orders-->
            {% block drop-drown %}
                {% if user.is_authenticated %}
                    <div class=" dropdown m-2 ">
                        <button class=" dropdown-toggle bi-person btn btn-outline-light" id="navbarDropdown" href="#"
                                role="button"
                                data-bs-toggle="dropdown" aria-expanded="false"></button>
                        <ul class="dropdown-menu" style="margin-left: 17%" aria-labelledby="navbarDropdown">

                            <form action="{% url 'customer:profile' %}" method="get">
                                <input class="btn btn-outline-dark dropdown-item" style="margin-left: 17%; width: 50%" type="submit"
                                       value="{% translate 'Profile' %}"/>
                            </form>
                            <li>
                                <hr class="dropdown-divider"/>
                            </li>
                            <li><a class="dropdown-item" style="width: 65%; margin-left: 17%; border-radius: 5px;"
                                   href="{% url 'orders:recent-orders' %}">  {% translate 'My orders' %} </a></li>
                            <form action="{% url 'customer:logout' %}">
                                <input class="btn btn-outline-dark dropdown-item" style="margin-left: 17%; width: 50%" type="submit"
                                       value="{% translate 'Logout' %}"/>
                            </form>

                        </ul>
                    </div>
                {% else %}
                    <form action="{% url 'customer:login' %}">
                        <input class="btn btn-outline-light m-1" type="submit" value="{% translate 'Login' %}"/>
                    </form>
                {% endif %}
                </div>
            {% endblock %}
        <a class="text-light"
           href="{% url 'change_lang' %}?lang=en&next=/en/{{ request.path|slice:'4:' }}">{% translate 'English' %}</a>
        <span class="text-light mx-2">|</span> <a class="text-light"
                                                  href="{% url 'change_lang' %}?lang=fa&next=/fa/{{ request.path|slice:'4:' }}">{% translate 'Persian' %}</a>
    </div>
</nav>
<div class="jumbotron bg-success p-3"
     style="text-align: center; border-bottom: solid black 5px">
    <h1>Welcome to our shop</h1>
    <h3 style="color: gold">See, Choose, Buy</h3>
</div>

{% block content %}

{% endblock %}
<!-- Footer-->
{#<footer class="py-5 bg-dark">#}
{#    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>#}
{#</footer>#}
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
{% block js %}
{% endblock %}
<script>
    var languege_code = '{{ LANGUAGE_CODE }}'

</script>
<script src="{% static 'auth/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'products/js/index.js' %}"></script>

</body>
</html>