online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from online_shop import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customers/', include('customers.urls')),
    # path('products/', include('products.urls')),
    # path('orders/', include('orders.urls')),
    path('api/v1/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.cart_actions import cart_add, cart_detail, cart_remove
from orders.views import OrdersHistoryView, RecentOrdersView, order, checkout_order, payment, invoice

app_name = 'orders'

urlpatterns = [
    path('orders-history/', OrdersHistoryView.as_view(), name="orders-history"),
    path('recent-orders/', RecentOrdersView.as_view(), name="recent-orders"),
    path('add_to_cart/<int:product_id>/', cart_add, name="cart_add"),
    path('cart_detail/', cart_detail, name="cart_detail"),
    path('cart_remove/<int:product_id>/', cart_remove, name="cart_remove"),
    path('order/', order, name="order"),
    path('checkout_order/', checkout_order, name="checkout_order"),
    path('payment/<int:order_id>/', payment, name="payment"),
    path('invoice/<int:order_id>/', invoice, name="invoice"),

]

products/api/urls.py
from django.urls import path

from products.api.views import PaginationView

urlpatterns = [
    path('', PaginationView.as_view(), name='api-product-list'),
    # path('product-images', ProductImageView.as_view(), name='api-product-image'),
]

products/urls.py
from django.urls import path

from products.views import IndexView, product_by_category,ProductDetailView

app_name = 'products'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category_product/<int:pk>/', product_by_category, name='product_category'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),

]

shop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import change_lang

urlpatterns = [
    path('change_lang', change_lang, name='change_lang'),
    # path('orders/', include('orders.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('customer/', include('customer.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('core.api.urls')),

)

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')), ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from translated_fields import TranslatedField
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Category(models.Model):
    name = TranslatedField(models.CharField(_('name'), max_length=250))
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, verbose_name=_('parent'),
                               related_name='children')

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return f"{self.name}"


class Attribute(models.Model):
    name = TranslatedField(models.CharField(_('name'), max_length=250))
    values = ArrayField(models.CharField(_('values'), max_length=10), null=True, blank=True)

    class Meta:
        verbose_name = _("Attribute")
        verbose_name_plural = _("Attributes")

    def __str__(self):
        return f"{self.name}"


class ProductImage(models.Model):
    title = TranslatedField(models.CharField(_('image'), max_length=100))
    image = models.ImageField(_('image'), upload_to='products/%Y/%m/%d/', max_length=500, )
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("ProductImage")
        verbose_name_plural = _("ProductImages")

    def __str__(self):
        return f"{self.title}"


class Product(models.Model):
    name = TranslatedField(models.CharField(_('name'), max_length=250))
    description = TranslatedField(models.TextField(_('description'), null=True, blank=True))
    price = models.FloatField(_('price'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    images = models.ManyToManyField(ProductImage, related_name='images', verbose_name=_('images'))
    number_of_products = models.PositiveIntegerField(_('number of products'), default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=_('category'),
                                 related_name='products')
    attributes = models.ManyToManyField(Attribute, verbose_name=_('Attributes'))

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name}"


# class Advertising(models.Model):
#     title = TranslatedField(models.CharField(_('title'), max_length=250))
#     image = models.ImageField(_('image'), upload_to='products/advertising/%Y/%m/%d/', max_length=500, )
#
#     class Meta:
#         verbose_name = _("Advertising")
#         verbose_name_plural = _("Advertisings")
#
#     def __str__(self):
#         return f"{self.title}"

products/api/views.py
from rest_framework import generics
from rest_framework.pagination import PageNumberPagination

from products.api.serializers import ProductSerializer
from products.models import Product, ProductImage


# class ProductImageView(generics.ListAPIView):
#     queryset = ProductImage.objects.all()
#     serializer_class = ProductSerializer


class LargeResultsSetPagination(PageNumberPagination):
    page_size = 8
    page_size_query_param = 'page_size'
    max_page_size = 8


class PaginationView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    pagination_class = LargeResultsSetPagination

products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.utils.translation import activate
from django.views import View
from django.views.generic import DetailView

from orders.forms import CartForm
from products.models import Product, Category


def change_lang(request):
    if request.method == "GET":
        activate(request.GET.get('lang'))
        return redirect(request.GET.get('next'))


class IndexView(View):
    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        context = {'products': products}
        return render(request, "products/index.html", context)


def product_by_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    return render(request, 'products/category_products.html', context={'category': category})


# class ProductDetailView(DetailView):
#     """
#         View for Customers See Product Detials and buy it
#         """
#     model = Product

class ProductDetailView(View):
    """
     View for Customers See Product Details and buy it
    """

    def get(self, request, pk, *args, **kwargs):
        try:
            product = Product.objects.get(id=pk)
            form = CartForm()
        except Product.DoesNotExist:
            return redirect(reverse("products:index"))
        return render(request, "products/product_detail.html", {
            'product': product, 'form': form
        })

templates/products/category.html
{% load i18n %}
{% load static %}
<ul class="dropdown-menu" aria-labelledby="navbarDropdown">

    {% for cat in categories %}
        {% if cat.parent == None %}
            <li>
            <a class="dropdown-item" href="{% url 'products:product_category' cat.id %}">
            {{ cat.name }}
            </a>
         {% if cat.children.all %}
             {% include 'products/category_loop.html' %}
          {% endif %}
            </li>
          {% endif %}
    {% endfor %}

</ul>

templates/products/category_loop.html
<ul class="dropdown-menu dropdown-submenu dropdown-submenu-left">
    {% for cat in cat.children.all %}
        <li>
            <a class="dropdown-item" href="{% url 'products:product_category' cat.id %}">{{ cat.name }}</a>
        {% if cat.children.all %}
             {% include 'products/category_loop.html' %}
          {% endif %}
        </li>
    {% endfor %}
</ul>

templates/products/category_products.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load humanize %}


{% block content %}
    <!-- Section-->
    <!-- display of products-->
    <section class="py-3">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-start">
                {% for product in category.products.all %}
                    <div class="col mb-5">
                        <div class="card h-100 text-light" style="border-radius: 10px">
                            <!-- Product images-->
                            <div id="{{ product.name }}" class="carousel slide " data-bs-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="carousel-item active p-5">
                                        <img src="{{ product.images.first.image.url }}" class="d-block w-100" alt="...">
                                    </div>
                                    {% for product_image in product.images.all %}
                                        <div class="carousel-item p-5">
                                            <img src="{{ product_image.image.url }}" class="d-block w-100" alt="...">
                                        </div>
                                    {% endfor %}
                                </div>

                            </div>
                            {#                        <img class="card-img-top" src="{{ product.image.urls }}" alt="..."/>#}
                            <!-- Product details-->
                            <div class="card-body bg-dark ">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>



                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-dark d-flex justify-content-center text-warning" style="border-bottom-left-radius: 10px; border-bottom-right-radius:10px; ">
                               <a href="{% url 'products:product_detail' product.id %}"  class="stretched-link"></a>
                                <!-- Product price-->
                                {{ product.price|floatformat|intcomma }} <span class="text-danger ml-2">{% translate 'Rial' %}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}

templates/products/index.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load humanize %}



{% block content %}
    <!-- Section-->
    <!-- display of products-->
    <section class="py-3">
        <div class="container px-4 px-lg-5 mt-5">
            <div id="block_image"
                 class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-start">
                <!--  Products are located here-->
            </div>
            <nav id="results" aria-label="Page navigation example">
                <ul class="pagination d-flex justify-content-center">
                    <!-- button of pagination-->
                </ul>
            </nav>
        </div>

    </section>
{% endblock %}

templates/products/product_detail.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% block style.css %}
    <link href="{% static 'products/css/product_detail.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
    <div class="container mt-5 mb-5">
        <div class="card bg-dark" style="border-radius: 10px; border: 2px solid white;">
            <div class="row g-0">
                <div class="col-md-6 border-end bg-dark">
                    <div class="d-flex flex-column justify-content-center bg-dark">
                        <div class="main_image"><img src="{{ product.images.first.image.url }}" id="main_product_image"
                                                     width="350"></div>
                        <div class="thumbnail_images bg-dark">
                            <ul id="thumbnail">
                                {% for image in product.images.all %}
                                    <li><img onclick="changeImage(this)" src="{{ image.image.url }}" width="70">
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 bg-dark" style="border-left: 2px solid white;">
                    <div class="p-3 right-side bg-dark text-light">
                        <div class="d-flex justify-content-center">
                            <h2>{{ product.name }}</h2>
                        </div>
                        <div class="mt-2 pr-3 content d-flex justify-content-center">
                            <h6>{{ product.description }}</h6>
                        </div>
                        <h2 class="d-flex justify-content-center mt-4 text-warning">{% translate 'price' %}: {{ product.price|floatformat|intcomma }} {% translate 'Rial' %}</h2>
                        <div class="d-flex justify-content-center mt-5"><span class="fw-bold" style="font-weight: bold; font-size: larger">{% translate 'Detail' %}</span></div>
                        <div class="mt-3">
                            <div>
                                <ul class="list-group">
                                    {% for attribute in product.attributes.all %}

                                        <li class="list-group-item d-flex justify-content-between align-items-center">
                                            {{ attribute.name }}
                                            <span style="font-weight: bold">{{ attribute.values.0 }}</span>
                                        </li>


                                    {% endfor %}
                                </ul>
                            </div>
                        </div>

                        <div class="buttons mt-5">
                            <form class="form-group" style="padding-left: 25%" method="post" action="{% url 'orders:cart_add' product.id %}">
                                {% csrf_token %}
                                <button class="bg-danger rounded" style="width: 12%" type="button" onclick="decrement()">-</button>
                                {{ form.product_count | attr:'type:number'|attr:'style:text-align: center'|attr:'id:quantity'|attr:'min=0' }}
                                <button class="bg-success rounded" style="width: 12%" type="button" onclick="increment()">+</button>
                                        <button type="submit"
                                                class="form-control w-50 btn btn-outline-success mt-4" style="margin-left: 8.5%">{% translate 'ADD TO CART' %}</button>

                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'products/js/product_detail.js' %}"></script>
{% endblock %}