customer/api/urls.py
from django.urls import path

from .views import RegisterAPIView, RequestPaswordResetEmail, CheckPasswordTokenView, SetNewPasswordAPIView, \
    SetChangePasswordView

urlpatterns = [
    path('', RegisterAPIView.as_view(), name='api-customer-list'),
    path('request-reset-email/', RequestPaswordResetEmail.as_view(), name='request-reset-email'),
    path('password-reset/<uidb64>/<token>/',
         CheckPasswordTokenView.as_view(), name='password-reset-confirm'),
    path('password-reset-complete/', SetNewPasswordAPIView.as_view(), name='password-reset-complete'),
    path('set-change-password', SetChangePasswordView.as_view(), name='set-change-password'),
    # path('edit-profile', EditProfileView.as_view(), name='edit-profile'),
]

customer/urls.py
from django.urls import path

from .views import CustomerLoginView, ChangePasswordView, RegisterView, CustomerProfileView, \
    SendLinkResetPasswordView, Set_New_Password, EditProfileView, customer_logout, add_address, remove_address

app_name = 'customer'

urlpatterns = [
    path('login/', CustomerLoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('logout/', customer_logout, name="logout"),
    path('reset-password/', SendLinkResetPasswordView.as_view(), name="reset-password"),
    path('set-new-password/<uidb64>/<token>/', Set_New_Password, name="set-new-password"),
    path('change-password/', ChangePasswordView.as_view(), name="change_password"),
    path('profile/', CustomerProfileView.as_view(), name="profile"),
    path('edit-profile/', EditProfileView.as_view(), name="edit_profile"),
    path('add-address/', add_address, name="add_address"),
    path('remove-address/<int:address_id>', remove_address, name="remove_address"),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from online_shop import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customers/', include('customers.urls')),
    # path('products/', include('products.urls')),
    # path('orders/', include('orders.urls')),
    path('api/v1/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.cart_actions import cart_add, cart_detail, cart_remove
from orders.views import OrdersHistoryView, RecentOrdersView, order, checkout_order, payment, invoice

app_name = 'orders'

urlpatterns = [
    path('orders-history/', OrdersHistoryView.as_view(), name="orders-history"),
    path('recent-orders/', RecentOrdersView.as_view(), name="recent-orders"),
    path('add_to_cart/<int:product_id>/', cart_add, name="cart_add"),
    path('cart_detail/', cart_detail, name="cart_detail"),
    path('cart_remove/<int:product_id>/', cart_remove, name="cart_remove"),
    path('order/', order, name="order"),
    path('checkout_order/', checkout_order, name="checkout_order"),
    path('payment/<int:order_id>/', payment, name="payment"),
    path('invoice/<int:order_id>/', invoice, name="invoice"),

]

shop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import change_lang

urlpatterns = [
    path('change_lang', change_lang, name='change_lang'),
    # path('orders/', include('orders.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('customer/', include('customer.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('core.api.urls')),

)

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')), ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from translated_fields import TranslatedField
from django.utils.translation import gettext_lazy as _


# Create your models here.


class CustomUser(AbstractUser):
    image = models.ImageField(_('image'), upload_to='profiles/', null=True, blank=True)
    is_active = models.BooleanField(_('active'), default=True)
    email = models.EmailField(_('email address'), unique=True)

    class Meta:
        verbose_name = _("Custom user")
        verbose_name_plural = _("Custom users")

    # def __str__(self):
    #     return f"{self.username}"


class Customer(CustomUser):
    addresses = models.ManyToManyField('Address', verbose_name=_('owner'))

    class Meta:
        verbose_name = _("Customer")
        verbose_name_plural = _("Customers")

    def __str__(self):
        return f"{self.username}"


class Staff(CustomUser):
    # user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Staff")
        verbose_name_plural = _("Staffs")

    def __str__(self):
        return f"{self.get_full_name()}"


class Address(models.Model):
    country = TranslatedField(models.CharField(_('country'), max_length=50, null=True, blank=True))
    province = TranslatedField(models.CharField(_('province'), max_length=50, null=True, blank=True))
    city = TranslatedField(models.CharField(_('city'), max_length=50, null=True, blank=True))
    house_number = models.PositiveIntegerField(_('house_number'), null=True, blank=True)
    exact_address = TranslatedField(models.TextField(_('exact address'), max_length=250))

    class Meta:
        verbose_name = _("Address")
        verbose_name_plural = _("Addresses")

    def __str__(self):
        return f"{self.exact_address}"

customer/api/views.py
import json

from django.contrib.auth import login
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.encoding import smart_bytes, smart_str, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from rest_framework import status, generics, permissions
from rest_framework.decorators import api_view
from rest_framework.exceptions import AuthenticationFailed
from rest_framework.permissions import IsAdminUser, AllowAny, IsAuthenticated
from rest_framework.response import Response
from .utils import Util
from django.utils.translation import gettext_lazy as _
from .serializers import CustomerRegisterSerializer, ResetPasswordEmailRequestSerializer, SetNewPasswordSerializer, \
    SetChangePasswordSerializer
from customer.models import Customer, CustomUser
from ..forms import CustomerRegisterForm


class RegisterAPIView(generics.ListCreateAPIView):
    queryset = Customer.objects.all()
    serializer_class = CustomerRegisterSerializer
    permission_classes = (AllowAny,)
    # permission_classes = [IsAdminUser]


class RequestPaswordResetEmail(generics.GenericAPIView):
    serializer_class = ResetPasswordEmailRequestSerializer

    def post(self, request):
        email = request.data['email']
        if Customer.objects.filter(email=email).exists():
            customer = Customer.objects.get(email=email)
            uidb64 = urlsafe_base64_encode(smart_bytes(customer.id))
            token = PasswordResetTokenGenerator().make_token(customer)
            current_site = get_current_site(request=request).domain
            relativeLink = reverse('customer:set-new-password', kwargs={
                'uidb64': uidb64,
                'token': token
            })
            absurl = 'http://' + current_site + relativeLink
            email_body = 'Hello,\n Use link below to reset your password \n' + absurl
            data = {
                'email_body': email_body,
                'to_email': customer.email,
                'email_subject': 'Reset your password'
            }
            Util.send_email(data)
            return Response({
                'success': 'we have sent you link to reset your password'
            }, status=status.HTTP_200_OK)
        return Response({'error': 'Don’t have an account?'}, status=status.HTTP_400_BAD_REQUEST)


class CheckPasswordTokenView(generics.GenericAPIView):
    def get(self, request, uidb64, token):
        try:
            id = smart_str(urlsafe_base64_decode(uidb64))
            customer = Customer.objects.get(id=id)

            if not PasswordResetTokenGenerator().check_token(customer, token):
                return Response({'error': 'Token is not valid, please request a new one'},
                                status=status.HTTP_401_UNAUTHORIZED)
            return Response({'success': True,
                             'message': 'credentials valid',
                             'uidb64': uidb64,
                             'token': token}, status=status.HTTP_200_OK)
        except DjangoUnicodeDecodeError as identifier:
            raise AuthenticationFailed('the reset link is invalid', 401)


class SetNewPasswordAPIView(generics.GenericAPIView):
    serializer_class = SetNewPasswordSerializer

    def patch(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response({'success': True, 'message': 'Password reset success'}, status=status.HTTP_200_OK)


class SetChangePasswordView(generics.GenericAPIView):
    serializer_class = SetChangePasswordSerializer
    # permission_classes = (permissions.IsAuthenticated,)


    def patch(self, request):
        username = request.data['username']
        customer = Customer.objects.get(username=username)
        serializer = self.get_serializer(data=request.data)
        # Check old password
        if not customer.check_password(request.data['old_password']):
            return Response({"old_password": _("Wrong password.")}, status=status.HTTP_400_BAD_REQUEST)
        if serializer.is_valid():
            # set_password also hashes the password that the user will get
            customer.set_password(request.data['new_password1'])
            customer.save()
            response = {
                'status': 'success',
                'message': _('Password updated successfully'),
            }

            return Response(response, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# class EditProfileView(generics.GenericAPIView):
#     serializer_class = EditProfileSerializer
#     # permission_classes = (permissions.IsAuthenticated,)
#
#     def put(self, request):
#         #old_username = request.data['old_username']
#         # username=request.data['username']
#         print(request.data['image'])
#         # customer = Customer.objects.get(username='morteza')
#         # serializer = self.get_serializer(data=request.data)
#         # print(request.data['image'])
#         # if serializer.is_valid():
#         #     customer.image=request.data['image']
#         #     customer.save()
#         #     response = {
#         #         'status': 'success',
#         #         'message': _('Password updated successfully'),
#         #     }
#         #     return Response(response, status=status.HTTP_200_OK)
#         return Response({'success':'fdlsfjsl'}, status=status.HTTP_400_BAD_REQUEST)

customer/views.py
import translated_fields
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.encoding import smart_str, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode
from django.views import generic, View
from django.views.generic import TemplateView

from customer.forms import CustomerLoginForm, CustomerRegisterForm, CustomerChangePassword, ResetPasswordSendEmail, \
    SetResetPassword, EditProfileForm

# Create your views here.
from customer.models import Customer, Address
from shop import settings


class CustomerLoginView(LoginView):
    """
    Customize Built-in View for Login Customers
    """

    authentication_form = CustomerLoginForm
    template_name = "customer/login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if 'next' in request.GET:
                return HttpResponseRedirect(request.GET['next'])
            return redirect('products:index')
        return super().get(request, *args, **kwargs)


class RegisterView(View):
    form_class = CustomerRegisterForm
    template_name = 'customer/register.html'
    initial = {'key': 'value'}

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})


class CustomerProfileView(LoginRequiredMixin, View):
    """
    View for Customer See Profile Detials and Edit it
    """

    def get(self, request, *args, **kwargs):
        try:
            customer = Customer.objects.get(id=request.user.id)
        except Customer.DoesNotExist:
            return redirect(reverse("customer:logout"))
        return render(request, "customer/profile.html", {
            'customer': customer,
        })


# class CustomerLogoutView(LoginRequiredMixin, LogoutView):
#     """
#     Customize Built-in View for Logout Customers
#     """
#     pass
def customer_logout(request):
    cart = request.session.get(settings.CART_SESSION_ID)
    logout(request)
    if cart:
        request.session[settings.CART_SESSION_ID] = cart
    return redirect(reverse('customer:login'))


class ChangePasswordView(LoginRequiredMixin, View):
    form_class = CustomerChangePassword
    template_name = 'customer/change_password.html'
    initial = {'key': 'value'}

    def get(self, request, *args, **kwargs):
        customer = Customer.objects.get(username=request.user)
        token = PasswordResetTokenGenerator().make_token(customer)
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 'token': token})


class SendLinkResetPasswordView(View):
    form_class = ResetPasswordSendEmail
    template_name = 'customer/reset_password.html'
    initial = {'key': 'value'}

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})


def Set_New_Password(request, uidb64, token):
    try:
        id = smart_str(urlsafe_base64_decode(uidb64))
        customer = Customer.objects.get(id=id)

        if not PasswordResetTokenGenerator().check_token(customer, token):
            return HttpResponse({'error': 'Token is not valid, please request a new one'},
                                status=401)
        form = SetResetPassword
        context = {'success': True,
                   'message': 'credentials valid',
                   'uidb64': uidb64,
                   'token': token,
                   'form': form}
        return render(request, 'customer/set_reset_password.html', context)
    except UnicodeDecodeError as e:
        raise DjangoUnicodeDecodeError('Token is not valid, please request a new one', *e.args)


class EditProfileView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        try:
            customer = Customer.objects.get(id=request.user.id)
        except Customer.DoesNotExist:
            return redirect(reverse("customer:logout"))
        form = EditProfileForm(instance=customer)
        return render(request, "customer/edit_profile.html", {
            'form': form,
        })

    def post(self, request, *args, **kwargs):
        try:
            customer = Customer.objects.get(id=request.user.id)
        except Customer.DoesNotExist:
            return redirect(reverse("customer:logout"))
        form = EditProfileForm(instance=customer, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse("customer:profile"))
        return render(request, "customer/edit_profile.html", {
            'form': form,
        })


@login_required
def add_address(request):
    if request.method == 'POST':
        customer = Customer.objects.get(id=request.POST['customer_id'])
        if request.POST['persian_address'] or request.POST['english_address']:
            new_address = Address.objects.create(exact_address_fa=request.POST['persian_address'],
                                                 exact_address_en=request.POST['english_address'])
            customer.addresses.add(new_address)
            customer.save()
            new_address.save()
    return redirect(reverse("customer:profile"))


@login_required
def remove_address(request, address_id):
    address = Address.objects.get(id=address_id)
    customer = Customer.objects.get(id=request.user.id)
    customer.addresses.remove(address)
    return redirect(reverse("customer:profile"))

templates/customer/profile.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{% translate 'Profile' %}{% endblock %}

{% block style.css %}
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'auth/css/profile.css' %}">
    <!--===============================================================================================-->
{% endblock %}
{% block drop-drown %}{% endblock %}
{% block content %}

    <div class=" emp-profile bg-dark text-light pt-3" style="margin-top: 4%; border-radius: 10px">
        <div class="row">
            <div class="col-3"><a type="submit" href="{% url 'customer:edit_profile' %}"
                                  style="margin: 2px;font-size: revert;"
                                  class="btn btn-outline-light w-75 ml-4 ">{% translate 'Edit Profile' %}</a></div>
            <div class="col-3"><a type="submit" href="{% url 'orders:recent-orders' %}"
                                  style="margin: 2px;font-size: revert;"
                                  class="btn btn-outline-light w-75 ml-4">{% translate 'Recent orders' %}</a></div>
            <div class="col-3"><a type="submit" href="{% url 'orders:orders-history' %}"
                                  style="margin: 2px;font-size: revert;"
                                  class="btn btn-outline-light w-75 ml-4 ">{% translate 'Order history' %}</a></div>
            <div class="col-3"><a type="submit" href="{% url 'customer:change_password' %}"
                                  style="margin: 2px;font-size: revert;"
                                  class="btn btn-outline-light w-75 ml-4 ">{% translate 'Change password' %}</a>
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-3">
            <div class="col-md-4">
                <div class="profile-img ">
                    {% if user.image %}
                        <img class="rounded-circle"
                             src="{{ user.image.url }}"
                             alt=""/>
                    {% else %}
                        <img class="rounded-circle"
                             src="/media/avatar.jpg/"
                             alt=""/>
                    {% endif %}

                </div>
            </div>

            <div class="row d-flex justify-content-center" style="color: gold">
                <div class="col-4 mt-3" style="text-align: center">
                    <h4>
                        {{ user.username }}
                    </h4>
                    <h6>
                    </h6>
                    <span class="proile-rating"
                          style="color: gold;font-size: medium">{% translate 'Last login' %} : </span>
                    <span>{{ user.last_login }}</span>
                </div>
            </div>
            <div class="row">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active text-danger" id="home-tab" data-toggle="tab" href="#home" role="tab"
                           aria-controls="home" aria-selected="true">
                            {% translate 'About' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-danger" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                           aria-controls="profile" aria-selected="false">{% translate 'Adresses' %}</a>
                    </li>
                </ul>
            </div>

            <div class="row d-flex justify-content-center pt-5">

                <div class="col-md-8">
                    <div class="tab-content profile-tab" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <div class="row d-flex justify-content-center">
                                <div class="col-md-2">
                                    <label class="text-success">{% translate 'first name : ' %}</label>
                                </div>
                                <div class="col-md-2">
                                    {% if user.first_name %}
                                        <p class="text-light">{{ user.first_name }} </p>
                                    {% else %}
                                        <p class="text-light">----------</p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row d-flex justify-content-center">
                                <div class="col-md-2">
                                    <label class="text-success">{% translate 'last name : ' %}</label>
                                </div>
                                <div class="col-md-2">
                                    {% if  user.last_name %}
                                        <p class="text-light"> {{ user.last_name }}</p>
                                    {% else %}
                                        <p class="text-light">----------</p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row d-flex justify-content-center">
                                <div class="col-md-2">
                                    <label class="text-success">{% translate 'Email : ' %}</label>
                                </div>
                                <div class="col-md-2">
                                    <p class="text-light">{{ user.email }}</p>
                                </div>
                            </div>
                            <div class="row">

                            </div>
                        </div>
                        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">

                            <table class="table table-bordered " style="text-align: center">
                                <thead class="bg-success text-white">
                                <tr>
                                    <th>#</th>
                                    <th>{% translate 'Address' %}</th>
                                    <th>{% translate 'Edit' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for address in customer.addresses.all %}
                                    <tr>
                                        <th class="bg-success text-white" scope="row">{{ forloop.counter }}</th>
                                        <td class="text-light">{{ address.exact_address }}</td>
                                        <td><a class="btn btn-outline-light"
                                               href="{% url 'customer:remove_address' address.id %}">{% translate 'Remove Address' %}</a>
                                        </td>

                                    </tr>
                                {% endfor %}


                                </tbody>
                            </table>
                            <div class="d-flex justify-content-center">
                                <a type="submit" href="" class="btn btn-outline-success" data-toggle="modal"
                                   data-target="#modal-add-address">{% translate 'Add Address' %}</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- large modal -->
        <div class="modal fade" id="modal-add-address" tabindex="-1" role="dialog" aria-labelledby="basicModal"
             aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content bg-dark">
                    <div class="modal-header">
                        <h4 class="modal-title text-warning" id="myModalLabel">{% translate 'Add Address' %}</h4>
                    </div>
                    <div class="modal-body p-1">
                        <div method="post" action="{% url 'customer:add_address' %}" class="mt-5">
                            {% csrf_token %}
                            <label for="persian_address">{% translate 'persian adress' %}</label>
                            <input type="text" class="form-control mt-2" id="persian_address" name="persian_address"
                                   placeholder="{% translate 'Enter exact address' %}">
                            <br>
                            <label for="english_address">{% translate 'english adress' %}</label>
                            <input type="text" class="form-control mt-2" id="english_address" name="english_address"
                                   placeholder="{% translate 'Enter exact address' %}">
                            <input type="hidden" id="customer_id" name="customer_id" value="{{ customer.id }}">
                            <div class="d-flex justify-content-center my-3">
                                <button type="submit"
                                        class="btn btn-outline-success">{% translate 'Add address' %}</button>
                            </div>
                            </form>

                        </div>
                        <div class="modal-footer d-flex justify-content-center">

                            <button type="button" class="btn btn-outline-danger " data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>


{% endblock %}