customer/urls.py
from django.urls import path

from .views import CustomerLoginView, ChangePasswordView, RegisterView, CustomerProfileView, \
    SendLinkResetPasswordView, Set_New_Password, EditProfileView, customer_logout, add_address, remove_address

app_name = 'customer'

urlpatterns = [
    path('login/', CustomerLoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('logout/', customer_logout, name="logout"),
    path('reset-password/', SendLinkResetPasswordView.as_view(), name="reset-password"),
    path('set-new-password/<uidb64>/<token>/', Set_New_Password, name="set-new-password"),
    path('change-password/', ChangePasswordView.as_view(), name="change_password"),
    path('profile/', CustomerProfileView.as_view(), name="profile"),
    path('edit-profile/', EditProfileView.as_view(), name="edit_profile"),
    path('add-address/', add_address, name="add_address"),
    path('remove-address/<int:address_id>', remove_address, name="remove_address"),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from online_shop import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customers/', include('customers.urls')),
    # path('products/', include('products.urls')),
    # path('orders/', include('orders.urls')),
    path('api/v1/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/api/urls.py
from django.urls import path

from orders.api.views import DiscountCodeView

urlpatterns = [
    path('discount-code', DiscountCodeView.as_view(), name='discount-code'),
]

orders/urls.py
from django.urls import path

from orders.cart_actions import cart_add, cart_detail, cart_remove
from orders.views import OrdersHistoryView, RecentOrdersView, order, checkout_order, payment, invoice

app_name = 'orders'

urlpatterns = [
    path('orders-history/', OrdersHistoryView.as_view(), name="orders-history"),
    path('recent-orders/', RecentOrdersView.as_view(), name="recent-orders"),
    path('add_to_cart/<int:product_id>/', cart_add, name="cart_add"),
    path('cart_detail/', cart_detail, name="cart_detail"),
    path('cart_remove/<int:product_id>/', cart_remove, name="cart_remove"),
    path('order/', order, name="order"),
    path('checkout_order/', checkout_order, name="checkout_order"),
    path('payment/<int:order_id>/', payment, name="payment"),
    path('invoice/<int:order_id>/', invoice, name="invoice"),

]

products/urls.py
from django.urls import path

from products.views import IndexView, product_by_category,ProductDetailView

app_name = 'products'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category_product/<int:pk>/', product_by_category, name='product_category'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),

]

shop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import change_lang

urlpatterns = [
    path('change_lang', change_lang, name='change_lang'),
    # path('orders/', include('orders.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('customer/', include('customer.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('core.api.urls')),

)

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')), ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
import datetime

import pytz
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from customer.models import Customer, Address
from products.models import Product
from translated_fields import TranslatedField

from django.utils.translation import gettext_lazy as _


# Create your models here.

class DiscountCode(models.Model):
    code = models.CharField(_("discount code"), max_length=100, unique=True)
    valid_from = models.DateTimeField(_("valid from"))
    valid_to = models.DateTimeField(_("valid to"))
    discount = models.IntegerField(_("discount"), validators=[MinValueValidator(0), MaxValueValidator(100)])
    owner = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name=_('owner'), related_name='codes')

    # ///////////
    class Meta:
        verbose_name = _("Discount code")
        verbose_name_plural = _("Discount codes")

    def __str__(self):
        return self.code


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name=_('costumer'))
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(_("order date"), default=pytz.utc.localize(datetime.datetime.now() + datetime.timedelta(days=2)))
    READY_TO_SEND = '0'
    SENDING = '1'
    DELIVERED = '2'
    STATUS = (
        (READY_TO_SEND, _("ready to send")),
        (SENDING, _("sending")),
        (DELIVERED, _("delivered")),
    )
    status = models.CharField(_("status"), max_length=50, choices=STATUS, default=READY_TO_SEND)
    discount = models.IntegerField(_("discount"), validators=[MinValueValidator(0), MaxValueValidator(100)], default=0)
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, verbose_name=_('address'))
    final_price = models.PositiveIntegerField(_("final price"))
    items = models.ManyToManyField('OrderItem', verbose_name=_('items'), )

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")
        ordering = ['-start_date']

    def __str__(self):
        return f'{self.customer.username} at {self.ordered_date}'


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_('product'))
    quantity = models.IntegerField(_("quantity"), default=1)

    class Meta:
        verbose_name = _("Order item")
        verbose_name_plural = _("Order items")

    def __str__(self):
        return f'{self.quantity} of {self.product.name}'

orders/forms.py
from django import forms


class CartForm(forms.Form):
    product_count = forms.IntegerField()
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/api/views.py
from datetime import datetime

import pytz
from rest_framework import generics, status
from rest_framework.response import Response
from django.utils.translation import gettext_lazy as _
from customer.models import Customer
from orders.api.serializers import DiscountCodeSerializer
from orders.cart import Cart
from products.models import Product


class DiscountCodeView(generics.GenericAPIView):
    serializer_class = DiscountCodeSerializer

    def post(self, request):
        code = request.data['code']
        cart = Cart(request)
        user_id = request.data['user_id']
        if not Customer.objects.get(id=user_id):
            return Response({'error': _('user_id does not exist')}, status=status.HTTP_400_BAD_REQUEST)
        customer = Customer.objects.get(id=user_id)
        for code_user in customer.codes.all():
            now = pytz.utc.localize(datetime.now())
            if code == str(code_user) and now < code_user.valid_to:
                final_price = cart.get_cart_total_price(code_user.discount)
                request.session['discount_code'] = code_user.id
                data = {
                    'final_price': final_price,
                    'discount': code_user.discount
                }
                return Response(data, status=status.HTTP_200_OK)
        return Response({'error': _('Discount code is not valid')}, status=status.HTTP_400_BAD_REQUEST)

orders/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views import View

from customer.models import Customer, Address
from orders.cart import Cart
from orders.forms import CartForm
from orders.models import Order, OrderItem, DiscountCode
from django.utils.translation import gettext_lazy as _


class OrdersHistoryView(LoginRequiredMixin, View):
    """
    View for Customer See orders history
    """

    def get(self, request, *args, **kwargs):
        try:
            orders_history = Order.objects.filter(customer__id=request.user.id, status='1')
        except Order.DoesNotExist:
            return redirect(reverse("customer:login"))
        return render(request, "orders/orders_history.html", {
            'orders_history': orders_history,
        })


class RecentOrdersView(LoginRequiredMixin, View):
    """
    View for Customer See orders history
    """

    def get(self, request, *args, **kwargs):
        try:
            recent_orders = Order.objects.filter(customer__id=request.user.id)[0:10]
        except Order.DoesNotExist:
            return redirect(reverse("customer:login"))
        return render(request, "orders/recent_orders.html", {
            'recent_orders': recent_orders,
        })


@login_required
def order(request):
    cart = Cart(request)
    for item in cart:
        item['update_count_form'] = CartForm(initial={'product_count': item['product_count'],
                                                      'update': True})
    customer = Customer.objects.get(id=request.user.id)
    return render(request, 'orders/cart_detail.html', {'cart': cart, 'customer': customer})


@login_required
def checkout_order(request):
    cart = Cart(request)
    if len(cart.cart) != 0:
        if 'discount_code' in request.session.keys():
            discount_code_id = request.session['discount_code']
            discount_code = DiscountCode.objects.get(id=discount_code_id)
            discount = discount_code.discount
            final_price = cart.get_cart_total_price(discount)
            del request.session['discount_code']
            discount_code.delete()

        else:
            discount = 0
            final_price = cart.get_cart_total_price()

        if request.method == 'POST':
            customer = Customer.objects.get(id=request.user.id)
            address = Address.objects.get(id=request.POST['order_address'])
            order = Order.objects.create(customer=customer, discount=discount, final_price=final_price,
                                         address=address, status='0')
            for item in cart:
                order.items.add(OrderItem.objects.create(product=item['product'],
                                                         quantity=item['product_count']
                                                         ))
        del request.session['cart']
        return render(request, 'orders/invoice.html', {'order': order})
    return render(request, 'orders/empty_cart.html')


@login_required()
def payment(request, order_id):
    Order.objects.filter(id=order_id).update(status='1')
    return redirect(reverse('orders:recent-orders'))


@login_required()
def invoice(request, order_id):
    order = Order.objects.get(id=order_id)
    return render(request, 'orders/invoice.html', {'order': order})

templates/orders/cart_detail.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% block style.css %}
    <link href="{% static 'orders/css/cart_detail.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
    <main class="page">
        {% if not cart.cart %}
            <div class="empty-cart p-5">
                <div class="container-fluid mt-100">
                    <div class="row mt-2 d-flex justify-content-center">
                        <div class="col-md-9">
                            <div class="card bg-dark" style="border-radius: 10px;">
                                <div class="card-body cart">
                                    <div class="col-sm-12 empty-cart-cls text-center">
                                        <h3 class="text-light"><strong>{% translate 'Your Cart is Empty' %}</strong></h3>
                                        <a href="{% url 'products:index' %}"
                                           class="btn btn-outline-light cart-btn-transform m-3"
                                           data-abc="true">{% translate 'shopping' %}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        {% else %}
            <section class="shopping-cart dark" style="background-color: darkcyan">
                <div class="container">
                    <div class="block-heading">
                    </div>
                    <div class="content">
                        <div class="row">
                            <div class="col-md-12 col-lg-8 bg-dark text-light">
                                {% for item in cart %}
                                    <div class="items">
                                        <div class="product">
                                            <div class="row">
                                                <div class="col-md-3">
                                                    <a href="{% url 'products:product_detail' item.product.id %}">
                                                        <img class="img-fluid mx-auto d-block image rounded"
                                                             src="{{ item.product.images.first.image.url }}"></a>
                                                </div>
                                                <div class="col-md-8">
                                                    <div class="info">
                                                        <div class="row">
                                                            <div class="col-md-5 product-name">
                                                                <div class="product-name">
                                                                    <p class="">{{ item.product.name }}</p>
                                                                    {% for attribute in item.product.attributes.all %}
                                                                        <div class="product-info">
                                                                            <div>{{ attribute.name }}<span
                                                                                    class="value ml-2">{{ attribute.values.0 }}</span>
                                                                            </div>
                                                                            <span class="text-warning">{{ item.product.price|floatformat|intcomma }}&nbsp;&nbsp;{% translate 'Rial' %}</span>
                                                                        </div>
                                                                    {% endfor %}
                                                                </div>
                                                                <a class="btn btn-outline-danger ml-5 mt-2" type="submit"
                                                                   href="{% url 'orders:cart_remove' item.product.id %}">{% translate 'Remove' %}</a>
                                                            </div>
                                                            <div class="col-md-4 quantity">
                                                                <form method="post"
                                                                      action="{% url 'orders:cart_add' item.product.id %}">
                                                                    {% csrf_token %}
                                                                    <label for="quantity">{% translate 'Quantity' %}:</label>
                                                                    {{ item.update_count_form.product_count | attr:'type:number'|attr:'id:quantity'| add_class:'form-control quantity-input' }}
                                                                    {{ item.update_count_form.update }}
                                                                    <input class="btn btn-outline-success" style="margin-top: 15%" type="submit"
                                                                           value="{% translate 'Update' %}">
                                                                </form>
                                                            </div>
                                                            <div class="col-md-3 price mt-4">
                                                                <span class="text-warning">{{ item.total_price|floatformat|intcomma }}&nbsp{% translate 'Rial' %}</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>

                            <div class="col-md-12 col-lg-4 bg-dark text-light">
                                <div class="summary bg-dark text-light" style="border-left: 2px solid white">
                                    <h1 class="text-success" style="text-align: center">{% translate 'invoice' %}</h1>
                                    {% if user.is_authenticated %}
                                        <div class="summary-item row"><span
                                                class="text col-6">{% translate 'total price' %}:</span><span
                                                class="price col-6 text-warning">{{ cart.get_cart_total_price|floatformat|intcomma }}</span></div>
                                        <div class="summary-item row"><span
                                                class="text col-7"
                                                id="discount_text">{% translate 'discount' %}: </span>&nbsp<span
                                                class="price col-4" id="discount"></span></div>
                                        <div class="summary-item row"><span
                                                class="text col-6"
                                                id="final_price_text">{% translate 'final price' %}: </span>&nbsp<span
                                                class="price col-5" id="final_price"></span></div>

                                        <div class="summary-item row"><span
                                                class="text col-12" id="error_text" style="color: red"></span></div>


                                        <form id="discount_code_form" action="" class="mt-5 mb-5">
                                            <label for="discount_code">{% translate 'Discount code' %}</label>
                                            <input type="text" class="form-control" id="discount_code"
                                                   name="discount_code"
                                                   placeholder="{% translate 'Enter discount code' %}">
                                            <input type="hidden" id="user_id" value="{{ user.id }}">
                                            <button type="submit"
                                                    class="btn btn-outline-success form-control ">{% translate 'Apply a discount code' %}</button>
                                        </form>

                                    {% else %}
                                        <div class="summary-item"><span
                                                class="text">{% translate 'total price' %}</span><span
                                                class="price">{{ cart.get_cart_total_price }}</span></div>
                                    {% endif %}
                                    {% if user.is_authenticated %}
                                        <form method="post" action="{% url 'orders:checkout_order' %}">
                                            {% csrf_token %}
                                            <label for="order_address">{% translate 'Address' %}</label>
                                            <select class="form-control" id="order_address" style="width: 200px"
                                                    name="order_address" required>
                                                {% for address in customer.addresses.all %}
                                                    <option class="form-control"
                                                            value="{{ address.id }}">{{ address.exact_address }}</option>
                                                {% endfor %}
                                            </select>
                                            <a type="submit" href="" class="btn btn-outline-success form-control mt-4"
                                               data-toggle="modal"
                                               data-target="#modal-add-address">{% translate 'Add Address' %}</a>
                                            <button type="submit"
                                                    class="btn btn-outline-success btn-lg btn-block mt-5">{% translate 'Order' %}</button>
                                        </form>

                                    {% else %}
                                        <a type="button" href="{% url 'orders:order' %}"
                                           class="btn btn-primary btn-lg btn-block mt-5">{% translate 'Order' %}</a>
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        {% endif %}
    </main>


     <!-- large modal for add address-->
    <div class="modal fade" id="modal-add-address" tabindex="-1" role="dialog" aria-labelledby="basicModal"
         aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">{% translate 'Add Address' %}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{% url 'customer:add_address' %}" class="mt-5">
                        {% csrf_token %}
                        <label for="persian_address">{% translate 'persian adress' %}</label>
                        <input type="text" class="form-control" id="persian_address" name="persian_address"
                               placeholder="{% translate 'Enter exact address' %}">
                        <label for="english_address">{% translate 'english adress' %}</label>
                        <input type="text" class="form-control" id="english_address" name="english_address"
                               placeholder="{% translate 'Enter exact address' %}">
                        <input type="hidden" id="customer_id" name="customer_id" value="{{ customer.id }}">

                        <button type="submit"
                                class="btn btn-primary mt-2">{% translate 'Add address' %}</button>

                    </form>

                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-outline-danger " data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>



{% endblock %}
{% block js %}
    <script src="{% static 'auth/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'orders/js/discount_code.js' %}"></script>
{% endblock %}

templates/orders/recent_orders.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content %}
    <div class="row d-flex justify-content-center w-100">
        <div class="col-9 bg-dark p-5 mt-5" style="border-radius: 10px">
            <table class="table table-bordered " style="text-align: center">
                <thead class="bg-success text-light">
                <tr>
                    <th>#</th>
                    <th>{% translate 'Start date' %}</th>
                    <th>{% translate 'status' %}</th>
                    <th>{% translate 'Actions' %}</th>
                    <th>{% translate 'Address' %}</th>
                    <th>{% translate 'More details' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for order in recent_orders %}
                    <tr>
                        <th class="bg-success text-light" scope="row">{{ forloop.counter }}</th>
                        <td class="bg-dark text-light">{{ order.start_date }}</td>
                        <td class="bg-dark text-light">{{ order.get_status_display }}</td>
                        {% if order.status == '0' %}
                            <td><a type="submit" href="{% url 'orders:invoice' order.id %}"
                                   class="btn btn-outline-success w-75 ">{% translate 'continue' %}</a></td>
                        {% else %}
                            <td><span></span></td>
                        {% endif %}
                        <td class="bg-dark text-light">{{ order.address.exact_address }}</td>
                        <td class="bg-dark text-light"><a type="submit" href="" class="btn btn-outline-light w-75 ml-4 " data-toggle="modal"
                               data-target="#modal-{{ order.id }}">{% translate 'order items' %}</a></td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    {% for order in recent_orders %}
        <!-- large modal -->
        <div class="modal fade" id="modal-{{ order.id }}" tabindex="-1" role="dialog" aria-labelledby="basicModal"
             aria-hidden="true">
            <div class="modal-dialog modal-xl">
                <div class="modal-content bg-dark" style="border-radius: 10px;">
                    <div class="modal-header">
                        <h4 class="modal-title text-warning" id="myModalLabel">{% translate 'Order details' %}</h4>

                    </div>
                    <div class="modal-body">
                        <table class="table table-bordered " style="text-align: center">
                            <thead class="bg-success text-light">
                            <tr>
                                <th>#</th>
                                <th>{% translate 'Name product' %}</th>
                                <th>{% translate 'Price product' %}</th>
                                <th>{% translate 'Quantity' %}</th>
                                <th>{% translate 'Image' %}</th>
                                <th>{% translate 'More description' %}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order_item in order.items.all %}
                                <tr>
                                    <th class="bg-success text-light" scope="row">{{ forloop.counter }}</th>
                                    <td class="text-light">{{ order_item.product.name }}</td>
                                    <td class="text-light">{{ order_item.product.price }} {% translate 'Rial' %}</td>
                                    <td class="text-light">{{ order_item.quantity }}</td>
                                    <td class="text-light"><img class="rounded" width="150" height="70"
                                             src="{{ order_item.product.images.first.image.url }}"></td>
                                    {% for attribute in order_item.product.attributes.all %}
                                        <td class="text-light">
                                            {{ attribute.name }}:{{ attribute.values }}<br>
                                        </td>
                                    {% endfor %}
                                </tr>

                            {% endfor %}

                            </tbody>
                        </table>

                        <p>
                            {% translate 'Address' %}: {{ order.address.exact_address }}
                        </p>

                    </div>
                    <div class="modal-footer justify-content-center">

                        <button type="button" class="btn btn-outline-danger "
                                data-dismiss="modal">{% translate 'Close' %}</button>
                    </div>
                </div>
            </div>
        </div>


    {% endfor %}


{% endblock %}